### ISSUE TITLE
flask-login and Werkzeug versions are incompatible

### ISSUE THREAD

**Issue by markstuart** [ckan/ckan-service-provider#57]
flask-login 0.5.0 and Werkzeug 2.1.x are not compatible, due to flask-login using a function that was removed in 2.1.0.

In our situation we are using the CKAN Datapusher library in a docker container, which imports the ckanserviceprovider web module. It started failing to run after a recent build, due to this error at startup:

```sh
Traceback (most recent call last):
  File "/etc/ckan/datapusher.wsgi", line 2, in <module>
    import ckanserviceprovider.web as web
  File "/usr/lib/ckan/datapusher/lib/python3.7/site-packages/ckanserviceprovider/web.py", line 13, in <module>
    import flask_login as flogin
  File "/usr/lib/ckan/datapusher/lib/python3.7/site-packages/flask_login/__init__.py", line 16, in <module>
    from .login_manager import LoginManager
  File "/usr/lib/ckan/datapusher/lib/python3.7/site-packages/flask_login/login_manager.py", line 24, in <module>
    from .utils import (login_url as make_login_url, _create_identifier,
  File "/usr/lib/ckan/datapusher/lib/python3.7/site-packages/flask_login/utils.py", line 13, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/usr/lib/ckan/datapusher/lib/python3.7/site-packages/werkzeug/security.py)
```

I've explicitly installed the newer version of flask-login to get around this for now, but hopefully this could be improved in this library?

**Comment by Zharktas** [comment]
It appears that flask-login 0.5.0 is just broken now as it does not specify upper limit of werkzeug versions which are compatible.  This could be fixed by adding werkzeug max version to requirements or by upgrading flask-login, which however drops py2 support. That probably is not an issue as datapusher is py3 compatible and is installed in its own virtualenv.

**Comment by amercader** [comment]
We can create a `requirements-py2.txt` file as we have for the dev ones and pin flask-login to 0.5.0 there, while upgrading to 0.6.1 on the main `requirements.txt`
@markstuart do you want to submit a PR?
